version: '3.8'
services:
  web:
    environment:
      SERVERNAME: dreamfactory.local

      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_USERNAME: df_admin
      DB_PASSWORD: df_admin
      DB_DATABASE: dreamfactory

      CACHE_DRIVER: redis
      CACHE_HOST: redis
      CACHE_DATABASE: 0
      CACHE_PORT: 6379

      APP_LOG_LEVEL: debug
      LOG_TO_STDOUT: "true"
      APP_DEBUG: "true"

#      DF_LICENSE_KEY:

      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: password
      ADMIN_FIRST_NAME: Admin
      ADMIN_LAST_NAME: DreamFactory
      ADMIN_PHONE_NUMBER: +1000000000

      APP_KEY: base64:ytnyqSYq/WiIOIjoy8iPLFfO9lulM7R0cUZSCxe9TtI=

    volumes:
      - df-storage:/opt/dreamfactory/storage
#      - ./../:/opt/dev/
    image: 116434471183.dkr.ecr.us-east-2.amazonaws.com/dreamfactory-gold:4.3.3
    ports:
      - "3000:80"
    depends_on:
      - mysql
      - redis

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamfactory
      MYSQL_USER: df_admin
      MYSQL_PASSWORD: df_admin
    image: mysql:5.7

  redis:
    image: redis

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    ports:
      - "8080:8080"

volumes:
  df-storage:
    driver: local
  hadoop-storage:
  namenode:
  datanode:
